version: '3'
services:
  flask:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "80:5000"
    environment:
      - FLASK_DEBUG=1
  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

volumes:
  dev-db-data: